export const subList2 =
    {
        "oriW": 900,
        "oriH": 500,
        "cover": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/cover.jpg",
        "subList": [
            {
                "type": 0,
                "backColor": "#FFFFFF"
            },
            {
                "type": 3,
                "title": "图片组件",
                "w": 1020,
                "h": 504,
                "x": -60,
                "y": -3,
                "rotate": 0,
                "useImg": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/2.png",
                "pro": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/2.png",
                "ori": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/2.png",
                "hovering": false,
                "mattingType": -1
            },
            {
                "type": 2,
                "title": "Summer fruit",
                "fontFamily": "'AlibabaPuHuiTi-Bold'",
                "fontSize": 8,
                "letterSpacing": 0,
                "lineHeight": 8,
                "color": "#333333",
                "backgroundColor": "",
                "fontStyle": "normal",
                "textDecoration": "none",
                "textAlign": "center",
                "fontWeight": "normal",
                "textShadow": 0,
                "flexDirection": 0,
                "w": 67,
                "h": 8,
                "x": 137,
                "y": 327,
                "rotate": 0,
                "hovering": false,
                "contenteditable": false
            },
            {
                "type": 2,
                "title": "Frest women",
                "fontFamily": "'AlibabaPuHuiTi-Bold'",
                "fontSize": 8,
                "letterSpacing": 0,
                "lineHeight": 8,
                "color": "#333333",
                "backgroundColor": "",
                "fontStyle": "normal",
                "textDecoration": "none",
                "textAlign": "center",
                "fontWeight": "normal",
                "textShadow": 0,
                "flexDirection": 0,
                "w": 67,
                "h": 8,
                "x": 137,
                "y": 341,
                "rotate": 0,
                "hovering": false,
                "contenteditable": false
            },
            {
                "type": 3,
                "title": "图片组件",
                "w": 6,
                "h": 6,
                "x": 136,
                "y": 313,
                "rotate": 0,
                "useImg": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/5.png",
                "pro": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/5.png",
                "ori": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/5.png",
                "hovering": false,
                "mattingType": -1
            },
            {
                "type": 3,
                "title": "图片组件",
                "w": 6,
                "h": 6,
                "x": 147,
                "y": 313,
                "rotate": 0,
                "useImg": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/6.png",
                "pro": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/6.png",
                "ori": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/6.png",
                "hovering": false,
                "mattingType": -1
            },
            {
                "type": 3,
                "title": "图片组件",
                "w": 6,
                "h": 6,
                "x": 158,
                "y": 313,
                "rotate": 0,
                "useImg": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/7.png",
                "pro": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/7.png",
                "ori": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/7.png",
                "hovering": false,
                "mattingType": -1
            },
            {
                "type": 3,
                "title": "图片组件",
                "w": 80,
                "h": 35,
                "x": 839,
                "y": 56,
                "rotate": 0,
                "useImg": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/8.png",
                "pro": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/8.png",
                "ori": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/8.png",
                "hovering": false,
                "mattingType": -1
            },
            {
                "type": 3,
                "title": "图片组件",
                "w": 110,
                "h": 50,
                "x": 36,
                "y": 288,
                "rotate": 0,
                "useImg": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/9.png",
                "pro": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/9.png",
                "ori": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/9.png",
                "hovering": false,
                "mattingType": -1
            },
            {
                "type": 3,
                "title": "图片组件",
                "w": 68,
                "h": 54,
                "x": -48,
                "y": 360,
                "rotate": 0,
                "useImg": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/10.png",
                "pro": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/10.png",
                "ori": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/10.png",
                "hovering": false,
                "mattingType": -1
            },
            {
                "type": 3,
                "title": "图片组件",
                "w": 419,
                "h": 452,
                "x": 377,
                "y": 21,
                "rotate": 0,
                "useImg": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/11.png",
                "pro": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/11.png",
                "ori": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/11.png",
                "hovering": false,
                "mattingType": -1
            },
            {
                "type": 3,
                "title": "图片组件",
                "w": 39,
                "h": 15,
                "x": 789,
                "y": 309,
                "rotate": 0,
                "useImg": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/12.png",
                "pro": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/12.png",
                "ori": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/12.png",
                "hovering": false,
                "mattingType": -1
            },
            {
                "type": 3,
                "title": "图片组件",
                "w": 37,
                "h": 10,
                "x": 136,
                "y": 82,
                "rotate": 0,
                "useImg": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/13.png",
                "pro": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/13.png",
                "ori": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/13.png",
                "hovering": false,
                "mattingType": -1
            },
            {
                "type": 3,
                "title": "图片组件",
                "w": 328,
                "h": 68,
                "x": 96,
                "y": 228,
                "rotate": 0,
                "useImg": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/14.png",
                "pro": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/14.png",
                "ori": "https://deeplor.oss-cn-hangzhou.aliyuncs.com/templates/poster900x500/6/layer/14.png",
                "hovering": false,
                "mattingType": -1
            },
            {
                "type": 2,
                "title": "fashion",
                "fontFamily": "'AlibabaPuHuiTi-Bold'",
                "fontSize": 36,
                "letterSpacing": 0,
                "lineHeight": 36,
                "color": "#000",
                "backgroundColor": "",
                "fontStyle": "normal",
                "textDecoration": "none",
                "textAlign": "center",
                "fontWeight": "normal",
                "textShadow": 0,
                "flexDirection": 0,
                "w": 217,
                "h": 36,
                "x": 138,
                "y": 150,
                "rotate": 0,
                "hovering": false,
                "contenteditable": false
            },
            {
                "type": 2,
                "title": "6月18日00:00开抢",
                "fontFamily": "'AlibabaPuHuiTi-Bold'",
                "fontSize": 16,
                "letterSpacing": 0,
                "lineHeight": 16,
                "color": "#FF7341",
                "backgroundColor": "",
                "fontStyle": "normal",
                "textDecoration": "none",
                "textAlign": "center",
                "fontWeight": "normal",
                "textShadow": 0,
                "flexDirection": 0,
                "w": 140,
                "h": 16,
                "x": 139,
                "y": 200,
                "rotate": 0,
                "hovering": false,
                "contenteditable": false
            },
            {
                "type": 2,
                "title": "new",
                "fontFamily": "'AlibabaPuHuiTi-Bold'",
                "fontSize": 35,
                "letterSpacing": 0,
                "lineHeight": 35,
                "color": "#000",
                "backgroundColor": "",
                "fontStyle": "normal",
                "textDecoration": "none",
                "textAlign": "center",
                "fontWeight": "normal",
                "textShadow": 0,
                "flexDirection": 0,
                "w": 110,
                "h": 35,
                "x": 138,
                "y": 102,
                "rotate": 0,
                "hovering": false,
                "contenteditable": false
            },
            {
                "type": 2,
                "title": "爱上新鲜感",
                "fontFamily": "'AlibabaPuHuiTi-Bold'",
                "fontSize": 34,
                "letterSpacing": 0,
                "lineHeight": 34,
                "color": "#FFFFFF",
                "backgroundColor": "",
                "fontStyle": "normal",
                "textDecoration": "none",
                "textAlign": "center",
                "fontWeight": "normal",
                "textShadow": 0,
                "flexDirection": 0,
                "w": 223,
                "h": 34,
                "x": 134,
                "y": 244,
                "rotate": 0,
                "hovering": false,
                "contenteditable": false
            }
        ]
    }


